GET {{url}}/users/
###


GET{{url}}/
###
GET {{url}}/users/1/favorites

###
POST {{url}}/
###
POST {{url}}/users/user2/favorites/2
###
POST {{url}}/users/user2/favorites
Content-Type: application/json

{
  "username": "hej",
  "name": "abc"
}

###
GET {{url}}/users/2/favorites

kka