GET {{url}}/users/
###


GET{{url}}/
###
GET {{url}}/users/1/favorites

###
POST {{url}}/
###
POST {{url}}/users/user1/favorites/spices/9
###
POST {{url}}/users/user1/favorites
Content-Type: application/json

{
  "username": "hej",
  "name": "abcde"
}

###
POST {{url}}/users/user1/favorites/cuisines/2
